using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1.Mw2
{
    public static class Insult
    {
        public static String Get_random_Insult()
        {
            String[] insults = {
    "A small dick's like a disability, so I won't make fun of you.",
    "After Covid is over, please carry on wearing your face mask so I do not have to look at you!",
    "All right. All right, I'll confess… I confess you're a bigger idiot than I thought you were.",
    "As an outsider, what do you think of the human race?",
    "At least Hitler killed himself.",
    "At least there's one good thing about your body. It isn't as ugly as your face.",
    "At least when I do a handstand my stomach doesn't hit me in the face.",
    "Aww, it's so cute when you try to talk about things you don't understand.",
    "Being a dick to everyone won't make yours any bigger.",
    "Brains aren't everything, in fact in your case their nothing.",
    "Brains aren't everything. In your case they're nothing.",
    "Calling you an idiot would be an insult to all stupid people.",
    "Did God design you from the leftover pieces in a trash can?",
    "Did you forget to brush your teeth? Your breath stinks!",
    "Do your keepers a huge favour: do a triple summersault through the air, and disappear up your own asshole.",
    "Don't be ashamed of who you are. That's your parent's job.",
    "Don't feel sad, don't feel blue, Frankenstein was ugly too.",
    "Don't you need a license to be that ugly?",
    "Earth is full! Go home!",
    "Eat shit and live!",
    "Even among idiots, you're lacking.",
    "Even the shower doesn't want to see you.",
    "Everyone's entitled to be stupid, but you're abusing the privilege",
    "Everything that comes out of your mouth is a lie, everything that goes in is a poop.",
    "Fake hair, fake nails, fake smile. Are you sure you weren't made in China?",
    "Filth! Scum! A by-product of dirt and vileness!",
    "Fuck you, you're ugly.",
    "Funny little thing, your brain! How do you get around in that thing?",
    "Gay? I'm straighter than the pole your mom dances on.",
    "Go and hide under something old!",
    "Go away! I was looking at something better than you!",
    "Go polish your crocs.",
    "God made you as an example of what not to do.",
    "Good story, but in what chapter do you shut the fuck up?",
    "Grab a straw, because you suck!",
    "Hang on, I'm still trying to decide whether I don't give a shit, or if I don't give a fuck!",
    "Hey, train wreck! This isn't your station!",
    "Hey, you have something on your chin. No, the 3rd one down.",
    "How about you get lost in the ocean instead?",
    "How many wrinkles does an asshole have? Smile! I'll count them!",
    "I bet you wear a nose ring because no one wants to put one on your finger.",
    "I bet your brain feels as good as new, seeing that you never use it.",
    "I burst my pimples at you and call your door-opening request a silly thing, you tiny-brained wipers of other people’s bottoms!",
    "I can't help imagining how much awesome the world would be if your dad had just pulled out.",
    "I could eat a bowl of alphabet soup and poop out a smarter statement than whatever you just said.",
    "I could get on your level, but I don't like being on my knees as much as you do!",
    "I do desire that we may be better strangers.",
    "I don’t want to talk to you no more, you empty-headed animal food trough wiper! I fart in your general direction! Your mother was a hamster and your father smelt of elderberries!",
    "I don't engage in mental combat with the unarmed.",
    "I don't exactly hate you, but if you were on fire and I had water, I'd drink it.",
    "I failed a spelling test because they asked me how to spell 'bitch' and I wrote down your name.",
    "I guess you prove that even god makes mistakes sometimes.",
    "I haven't seen you run that fast since Twinkies went on sale!",
    "I hear when you were a child your mother wanted to hire somebody to take care of you, but the mafia wanted too much.",
    "I heard you received a brain transplant but it rejected your body.",
    "I hope one day you choke on the shit you talk!",
    "I hope you step on legos",
    "I hope your next blowjob is from a shark!",
    "I hope your next period happens in a shark tank!",
    "I in no way advocate violence... but sometimes, a slap is worth a thousand words.",
    "I just stepped in something that was smarter than you and smelled better too.",
    "I know You're not as stupid as you look, Nobody could be!",
    "I love what you've done with your hair. How do you get it to come out of your nostrils like that?",
    "I see you were so impressed with your first chin that you added two more.",
    "I set my standards pretty low, so I'm never disappointed.",
    "I think it's mating season at the zoo, so go back to the orangutans and get married!",
    "I thought of you today. It reminded me to take the garbage out.",
    "I throw up when I look at you!",
    "I was pro-life. Then I met you.",
    "I was today years old when I realized I didn't like you.",
    "I wasn't born with enough middle fingers to let you know how I feel about you.",
    "I wish I bleached my eyes before I saw your face!",
    "I would ask how old you are, but I know you can't count that high.",
    "I would burn you but burning trash is bad for the environment.",
    "I would never date you. I'm lonely, not desperate.",
    "I would slap you, but shit splatters!",
    "I'd agree with you but then we'd both be wrong.",
    "I'd give you a nasty look but you've already got one.",
    "I'd like to kick you in the teeth but why improve your looks?",
    "I'd offer you some gum but your smiles got plenty of it.",
    "I'd prefer a battle of wits, but you appear unarmed.",
    "I'd say you're funny, but looks aren't everything.",
    "I'd tell you to go stuff yourself, but that would be cruel and unusual punishment.",
    "I'd tell you to go to hell, but I work there and don't want to see you every day.",
    "If brains were gold, you'd be poorer than a homeless person!",
    "If I had a dollar for every time you said something smart, I'd be broke.",
    "If I had a face like yours, I'd sue my parents.",
    "If I throw a stick, would you leave?",
    "If I wanted a bitch I'd have bought a dog.",
    "If I wanted to hear from an asshole, I'd fart.",
    "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
    "If I wanted to listen to an asshole, I'd fart.",
    "If I were your mirror I would commit suicide.",
    "If I'm ever in need of advice from a psychotic potato dwarf, you'll be the first to know.",
    "If laughter is the best medicine, your face must be curing the world.",
    "If my dog had your face I would shave his ass and teach him to walk backwards.",
    "If the human body is 75% water, how can you be 100% salt?",
    "If there was a vote for 'least likely to succeed' you'd win first prize.",
    "If you don't think I ain't makin' a mental list of all your fuckin' bullshit...",
    "If you have a problem with me, write the problem on a piece of paper, fold it, and shove it up your ass.",
    "If you were anymore inbred, you would make a sandwich!",
    "If you were the trophy at the end of the race, I'd run backwards!",
    "If you were twice as smart, you'd still be stupid!",
    "If your IQ was multiplied by anything it would still be 0.",
    "If your parents were to divorce, would they still be brother and sister?",
    "If your ugliness was measured in bricks, you would own The Great Wall of China",
    "If you're gonna be a smartass, first you have to be smart. Otherwise, you're just an ass.",
    "I'll never forget the first time we met. But I'll keep trying.",
    "I'm jealous of all the people who haven't met you!",
    "I'm jealous of people that don't know you!",
    "I'm not a photographer, but I can picture you better elsewhere",
    "I'm not questioning your honour. I'm denying its existence.",
    "I'm sorry your dad beat you instead of cancer.",
    "I'm surrounded by idiots... Or, wait, that's just you.",
    "Is it sad that your theme song might as well have a 0/0 signature?",
    "Is it true when you were born the doctor turned around and slapped your mother?",
    "Is that your face? Or did your neck just throw up?",
    "Is your butt jealous of the amount of shit that just came out of your mouth?",
    "It looks like your face caught fire and someone tried to put it out with a hammer.",
    "It's better to let someone think you are an idiot than to open your mouth and prove it.",
    "It's not pretty watching a jackass trying to eat a pomegranate.",
    "Jesus might love you, but everyone else thinks you're an idiot.",
    "Just Because You Have The Emotional Range Of A Teaspoon Doesn't Mean We All Have!",
    "Keep rolling your eyes. Maybe you'll find a brain back there!",
    "Life is full of disappointments and I just added you to the list.",
    "Look, you aren't funny. Your life is just a joke.",
    "May both sides of your pillow be uncomfortably warm.",
    "May your wife give birth to a centipede so you have to work for shoes all your life.",
    "Mirrors can't talk, and lucky for you they can't laugh either.",
    "My middle finger salutes you!",
    "Nice shirt, what brand is it? Clearance?",
    "No, I checked my receipt. I didn't buy any of your bullshit!",
    "N'Sync said it best, “BYE, BYE, BYE!”",
    "Oh go on. Crack a smile. I want to see if your eyebrows drop off!",
    "Oh, what? Sorry. I was trying to imagine you with a personality.",
    "Okay, chopzilla, listen up, 👍 This little piggy went to the market. 🖕 This little piggy stayed home... And if this little piggy doesn't shut the fuck up, I'm gonna shove my foot up your fucking ass",
    "One more wrinkle and you'd pass for a prune.",
    "Out of 100,000 sperm, you were the fastest?",
    "People clap when they see you. They clap their hands over their eyes!",
    "Please, I could remove 90% of your 'beauty' with a tissue!",
    "Remember to look both ways before you go fuck yourself!",
    "Roses are red, I don't give a fuck! Your mum and dad are fucking crazy for having you, ya fucking spunk bubble. Shut up!",
    "Roses are red, poo is brown, shut the fuck up, and sit the fuck down.",
    "Roses are red, violets are blue. I can't wait to punch you...",
    "Save your breath - you're going to need it to blow up your date.",
    "Shut up, you'll never be the man your mother is!",
    "Shut up. Just... shut up...",
    "So tell me... Is your ass aware that your head has moved in?",
    "Some babies were dropped on their heads but you were clearly thrown at a wall.",
    "Some cause happiness wherever they go; others whenever they go.",
    "Someday you will go far, and I hope you stay there.",
    "Someone once said You're pretty as a picture... I agree I would love to hang you.",
    "Somewhere out there is a tree working very hard to replace the oxygen you consume. Now go apologize to it!",
    "Somewhere, somehow, you are robbing a village of their idiot.",
    "Sorry I didn't get that, I don't speak idiot.",
    "Sorry, I can't hear you over how annoying you are.",
    "Stupidity is not a crime so you are free to go.",
    "Suck Devilcock in hell!",
    "Tell your mom to make your mac n cheese, I'll be home soon.",
    "The 80's called, they want their haircut back.",
    "The clothes you wear are so ugly even a scarecrow wouldn't wear them.",
    "The last time I saw a face like yours I fed it a banana.",
    "The last time I saw something like you, I flushed it!",
    "The next word that comes out of your mouth better be some brilliant fuckin mark twain shit cause it's definitely getting chiselled on your tombstone!",
    "The only accessory that could save your outfit is an invisibility cloak!",
    "The only positive thing about you is your HIV status.",
    "The only reason your partner likes you is because they were taught to enjoy the little things in life.",
    "The only thing that goes erect when I'm near you is my middle finger.",
    "The zoo called. They're wondering how you got out of your cage.",
    "They say people get what they deserve. In your case, it's a participation trophy.",
    "Thou art as fat as butter!",
    "Twatface!",
    "Twinkle twinkle little star, I want to hit you with my car, Throw you off a cliff so high, I hope you break your neck and die.",
    "Twinkle twinkle little star, You're the  nastiest thing so far!",
    "Twinkle Twinkle little star, you're the ugliest I've seen so far!",
    "Twinkle twinkle little whore, close your legs, they're not a door.",
    "U. G. L. Y. You ain't got no alibi, you ugly! Eh! Hey! You ugly!",
    "Was one of your parents, a Naked Mole Rat? You're ugly as fuck!",
    "We all sprang from apes, but you did not spring far enough.",
    "What doesn't kill you, disappoints me...",
    "What the fucking hell are you, you great gangly fuck-knuckle twat, greasy-haired cunt bag. Fuck you.",
    "What's the difference between you and an egg? Eggs get laid!",
    "When I see your face there's not a thing I would change... Except for the direction I'm walking in.",
    "When the airforce needs extra landing space they should just rent out your forehead.",
    "When you look in the mirror, say hi to the clown you see in there for me, would ya?",
    "When you were born your mom threw you out the window and the window threw you back.",
    "When you were born, the police arrested your dad, the doctors slapped your mum, animal control euthanized your sibling, and A&E made a documentary that saved your life.",
    "When you were born, the police said you were a piece of shit. They shot you.",
    "Who lit the fuse on your tampon?",
    "Why don't you check up on eBay and see if they have a life for sale!",
    "Why is it acceptable for you to be an idiot, but not for me to point it out?",
    "With a face like yours, I wish I was blind!",
    "You are an insult upon insults of a booble of an assortment.",
    "You are like a cloud. When you disappear, it's a beautiful day.",
    "You are living proof that manure can sprout legs and walk.",
    "You are the human version of period cramps.",
    "You bring everyone so much joy... when you leave the room.",
    "You conserve toilet paper by using both sides.",
    "You dense, irritating, miniature beast of a burden!",
    "You do realize makeup isn't going to fix your stupidity?",
    "You foul, loathsome, evil little cockroach!",
    "You have the charisma of a damp towel.",
    "You have the charm of a dead battery.",
    "You have the kinds of looks that make people talk about your personality.",
    "You have the memory of a goldfish, only less useful.",
    "You have the perfect face for radio.",
    "You have the subtlety of a brick and the depth of a shot glass!",
    "You know, you are a classic example of the inverse ratio between the size of the mouth and the size of the brain.",
    "You look like a before picture.",
    "You look like a rock smashed into a pile of sand, rolled into a blunt, and got smoked through an asthma inhaler.",
    "You look like the after picture of a meth ad.",
    "You look like the result of pressing random on the character creation menu.",
    "You may look like an idiot and talk like an idiot but don't let that fool anyone. You're really is an idiot.",
    "You must have been born on a highway because that's where most accidents happen.",
    "You only annoy me when you're breathing.",
    "You prefer three left turns to one right turn.",
    "You remind me of a penny. Two-faced, and not worth much!",
    "You should introduce your upper lip to your lower lip sometime, and shut the fuck up!",
    "You should use gorilla glue instead of a chapstick!",
    "You should wear a muzzle. No reason.",
    "You shouldn't play hide and seek, no one would look for you.",
    "You walk behind your boss reaching through his legs and supporting his testicles.",
    "You were so ugly that when you were born the doctor put tinted windows on your incubator.",
    "You'd be suicidal if you felt as bad as you look.",
    "You'll never be the man your mother is.",
    "Your advice is about as useful as a paper-mache bomb shelter.",
    "Your birth certificate is an apology letter from the condom factory.",
    "Your body fat is about as evenly distributed as wealth in the US economy.",
    "Your brain's so minute that if a hungry cannibal cracked your head open, there wouldn't be enough to cover a small water biscuit.",
    "Your face could scare the shit out of a toilet.",
    "Your face looks like something I would draw with my non-dominant hand.",
    "Your face makes onions cry.",
    "Your family tree must be a cactus because everyone on it is a prick.",
    "Your head shape looks like a broken condom.",
    "Your intelligence is like a black hole, it's non-existent.",
    "Your IQ is lower than the Mariana Trench.",
    "Your jokes are like your personality, dry and lacking substance.",
    "Your lips keep moving but I don't speak stupid.",
    "Your mother mates with reindeer!",
    "Your mother was a hamster and your father smelt of elderberries.",
    "Your mum is so fat, she has to wear 2 watches because she covers two time zones!",
    "Your parents must be siblings, that's the only explanation for your genetic malfunction.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "Your value doesn't even amount to the juice squeezed from an old whore's soiled tampon!",
    "You're a failed abortion whose birth certificate is an apology letter from the condom factory.",
    "You're a fucking idiot.",
    "You're a grey sprinkle on a rainbow cupcake!",
    "You're a knob-munching bumblefuck.",
    "You're about as useful as a phone with no batteries.",
    "You're as beautiful as a pig in a mud bath!",
    "You're as beautiful as dog shit!",
    "You're as bright as a black hole and twice as dense!",
    "You're as ugly as Jason Voorhees in 'Friday The 13th Part 8: Jason Takes Manhattan'!",
    "You're happy to believe in something that's invisible, but if it's staring you in the face, nope, can't see it. There's a scientific explanation for that: you're thick.",
    "You're kind of like Rapunzel except instead of letting down your hair, you let down everyone in your life.",
    "You're like a cloud, when you go away the day gets brighter",
    "You're like a light switch, even a little kid can turn you on.",
    "You're like dobby from Harry Potter, only people won't be sad when you die in the seventh book.",
    "You're like Mondays, everyone hates you.",
    "You're like school in July. No class.",
    "You're like STDs, nobody wants you, everyone hates you and it proves your parents should have used protection.",
    "You're like the human version of a headache!",
    "You're my favourite, you are. You are the best, you know why? Cos you're so thick! You're Mr Thick Thick Thickety Thickface from Thicktown. And so's your dad!",
    "You're not a model. You're a bitch with a smart phone and 37 editing apps. Shut the fuck up!",
    "You're not completely useless, you can always serve as a bad example.",
    "You're not worth roasting.",
    "You're not yourself today, I noticed the improvement immediately.",
    "You're proof evolution can go in reverse.",
    "You're proof that God has a sense of humour.",
    "You're so annoying even the flies stay away from your stench.",
    "You're so boring, even your shadow leaves you to go do something more exciting.",
    "You're so boring, you make paint drying look like a thrilling experience.",
    "You're so dumb that you got hit by a parked car.",
    "You're so dumb you make Kim Kardashian seem smart!",
    "You're so dumb, your dog teaches you tricks.",
    "You're so fake, even Barbie is jealous!",
    "You're so fake, even China rejected your knockoff version.",
    "You're so fat the only letters of the alphabet you know are KFC.",
    "You're so fat you could sell shade.",
    "You're so fat you need cheat codes to play Wii Fit.",
    "You're so fat, that you have your own gravitational pull!",
    "You're so fat, you make the galaxy look like it's on the molecular scale.",
    "You're so fat, you need cheat codes to play Wii Fit!",
    "You're so forgetful, you need GPS to find your own memory.",
    "You're so slow, time waits for you like a polite stranger waiting for a bus.",
    "You're so slow, you make a snail look like Usain Bolt.",
    "You're so stupid I don't have the time or the crayons to explain this to you.",
    "You're so stupid you tried to wake a sleeping bag.",
    "You're so stupid, it takes you an hour to cook minute rice.",
    "You're so stupid, you'd trip over a cordless phone.",
    "You're so stupid. That's just it really. I got nothing else to add.",
    "You're so ugly that when your own mother dropped you off at school she got a fine for littering!",
    "You're so ugly, Hello Kitty said goodbye to you!",
    "You're so ugly, that when you popped out the doctor said 'Aww what a treasure', and your mom said 'Yeah let's bury it'",
    "You're so ugly, that your own mother didn't even turn up to your birth!",
    "You're so ugly, when you got robbed, the robbers made you wear their masks.",
    "You're so ugly, when you look in the mirror, your reflection looks away.",
    "You're so ugly, when you threw a boomerang it didn't come back.",
    "You're so ugly, when your mum dropped you off at school, she got a fine for littering!",
    "You're so ugly, you make blind kids cry.",
    "You're so ugly, you make blind people wish they were deaf too.",
    "You're so ugly, you make onions cry.",
    "You're so ugly, you scared the crap out of the toilet.",
    "You're so ugly, your brain would fit in a candy cane.",
    "You're so ugly, your face makes the news look good.",
    "You're so ugly, your mother would run for the door if she saw you.",
    "You're so ugly, your mother would throw you in the water with a stone.",
    "You're so unoriginal, you make a copy machine look like a creative genius.",
    "You're the equivalent to a piece of shit at the bottom of my shoe!",
    "You're the reason the gene pool needs a lifeguard.",
    "You're the reason they invented double doors!",
    "You're the reason why protection exists!.",
    "You're the reason your dad drinks.",
    "You're the reason your nan gets bullied at bingo!",
    "You're the result of searching for yourself on Wish.com!",
    "You're what the French call: 'Les incompetents'.",
    "You've got less meat in your pants than there is in a vegetarian restaurant.",
    "I\'ll speak to you in a language you understand: 'Idiot you are!'",
    "Repeat after me: 'I am dumb!'",
    "When you were born, the doctor came out to the waiting room and said to your dad, 'I\'m very sorry. We did everything we could. But he pulled through.'",
    "You stare at frozen juice cans because they say, 'concentrate'.",
            };

            int size = insults.Count();

            return insults[StaticRandom.Instance.Next(0, size - 1)]; ;
        }
    }
}
